# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: wms-zenith
    ports:
      - "3030:3030" # A porta no seu .env de exemplo era 3000, ajuste se necessário
    volumes:
      - .:/app
    restart: always
    
    # REMOVIDO:
    # env_file:
    #   - .env
      
    # ADICIONADO:
    # Insira suas variáveis de ambiente diretamente aqui.
    environment:
      # Endereço da API
      - SANKHYA_API_URL=https://api.sankhya.com.br
      
      # Credenciais de autenticação
      - SANKHYA_APPKEY=
      - SANKHYA_TOKEN=
      - SANKHYA_USERNAME=
      - SANKHYA_PASSWORD=
      
      # Chave secreta da sessão
      - JWT_SECRET=
      
      # Porta do servidor
      - PORT=3030