name: Notify on New Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification
      run: |
        curl -X POST \
        -H "Authorization: key=${{ secrets.FCM_SERVER_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{
          "to": "/topics/new_releases",
          "notification": {
            "title": "Nova versão disponível!",
            "body": "A versão ${{ github.event.release.tag_name }} do ZENITH WMS está disponível para download."
          }
        }' \
        https://fcm.googleapis.com/fcm/send